server {
    listen 80;
    listen [::]:80;

    server_name localhost;
    server_tokens off;
    
    sendfile on;
    tcp_nodelay on;
    tcp_nopush on;

    gzip on;
    gzip_proxied any;
    gzip_vary on;
    gzip_min_length 256;
    gzip_comp_level 5;
    gzip_types text/css text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html;

        try_files $uri $uri/ /index.html;
    }
}